# Generated by Django 5.2.17 on 2026-08-06 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem', models.CharField(choices=[('GOOGLE_PLACES', 'Google Places'), ('CNPJ', 'Dataset CNPJ (Receita Federal)'), ('MANUAL', 'Cadastro manual')], max_length=20)),
                ('origem_id', models.CharField(help_text='place_id (Places) ou CNPJ (Receita)', max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, default='', max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=255)),
                ('cnpj', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('segmento', models.CharField(choices=[('SALAO', 'Salão de beleza'), ('ESTETICA', 'Clínica de estética'), ('NAIL', 'Nail designer'), ('LASH', 'Lash designer'), ('SOBRANCELHA', 'Design de sobrancelha'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('termo_busca', models.CharField(blank=True, default='', max_length=200)),
                ('endereco', models.TextField(blank=True, default='')),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('instagram', models.CharField(blank=True, default='', max_length=255)),
                ('website_url', models.TextField(blank=True, default='')),
                ('tem_site_real', models.BooleanField(blank=True, null=True)),
                ('site_evidencia', models.TextField(blank=True, default='')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('total_avaliacoes', models.PositiveIntegerField(blank=True, null=True)),
                ('status_funil', models.CharField(choices=[('NOVO', 'Novo (curadoria)'), ('INICIAR', 'A iniciar'), ('EM_ANDAMENTO', 'Em andamento'), ('REMARKETING', 'Remarketing'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='NOVO', max_length=20)),
                ('ativo_no_funil', models.BooleanField(default=False, help_text='False enquanto está na curadoria ou já em coluna terminal')),
                ('proximo_contato_em', models.DateTimeField(blank=True, help_text='Vencido = reaparece na tela de follow-up', null=True)),
                ('revisado_manualmente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'prospect',
                'verbose_name_plural': 'prospects',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp (manual)'), ('INSTAGRAM', 'Instagram (manual)'), ('TELEFONE', 'Telefone'), ('PRESENCIAL', 'Presencial'), ('EMAIL', 'E-mail')], max_length=20)),
                ('anotacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='leads.prospect')),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'interações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('JA_TEM_SITE', 'Já tem site'), ('SEM_INTERESSE', 'Sem interesse'), ('SEM_VERBA', 'Sem verba'), ('FECHADO', 'Estabelecimento fechado'), ('FORA_DO_PERFIL', 'Fora do perfil (ex: barbearia)'), ('SEM_RESPOSTA', 'Sem resposta após tentativas'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('banido', models.BooleanField(default=False, help_text='Não retorna ao funil nem em nova varredura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartes', to='leads.prospect')),
            ],
            options={
                'verbose_name': 'descarte',
                'verbose_name_plural': 'descartes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Quadrante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('rotulo', models.CharField(help_text='Q1..Qn, Q1 no canto sudoeste', max_length=10)),
                ('sul', models.FloatField()),
                ('oeste', models.FloatField()),
                ('norte', models.FloatField()),
                ('leste', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'quadrante',
                'verbose_name_plural': 'quadrantes',
                'ordering': ['cidade', 'rotulo'],
                'constraints': [models.UniqueConstraint(fields=('cidade', 'estado', 'rotulo'), name='uniq_quadrante_por_cidade')],
            },
        ),
        migrations.CreateModel(
            name='Varredura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('termo_busca', models.CharField(help_text='Texto literal enviado à API, ex: "salão de beleza em Maringá PR"', max_length=200)),
                ('segmento', models.CharField(choices=[('SALAO', 'Salão de beleza'), ('ESTETICA', 'Clínica de estética'), ('NAIL', 'Nail designer'), ('LASH', 'Lash designer'), ('SOBRANCELHA', 'Design de sobrancelha'), ('OUTRO', 'Outro')], max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RODANDO', 'Rodando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('total_requisicoes', models.PositiveIntegerField(default=0)),
                ('total_encontrados', models.PositiveIntegerField(default=0)),
                ('total_sem_site', models.PositiveIntegerField(default=0)),
                ('total_novos', models.PositiveIntegerField(default=0)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('quadrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varreduras', to='leads.quadrante')),
            ],
            options={
                'verbose_name': 'varredura',
                'verbose_name_plural': 'varreduras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='prospect',
            name='varredura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='leads.varredura'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('qualificacao', models.CharField(blank=True, default='', max_length=120)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='leads.prospect')),
            ],
            options={
                'verbose_name': 'sócio',
                'verbose_name_plural': 'sócios',
                'constraints': [models.UniqueConstraint(fields=('prospect', 'nome'), name='uniq_socio_por_prospect')],
            },
        ),
        migrations.AddIndex(
            model_name='varredura',
            index=models.Index(fields=['-criado_em'], name='leads_varre_criado__13f7de_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['status_funil', 'ativo_no_funil'], name='leads_prosp_status__956ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['tem_site_real'], name='leads_prosp_tem_sit_0fec4a_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['proximo_contato_em'], name='leads_prosp_proximo_30ad4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(fields=('origem', 'origem_id'), name='uniq_prospect_por_origem'),
        ),
    ]
