# Generated by Django 5.2.17 on 2026-08-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarte',
            name='origem_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cópia do identificador de origem — mantém o veto se o prospect sumir', max_length=255),
        ),
        migrations.AlterField(
            model_name='descarte',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descartes', to='leads.prospect'),
        ),
    ]
