# Generated by Django 5.2.17 on 2026-08-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_descarte_origem_id_alter_descarte_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='varredura',
            name='fonte',
            field=models.CharField(choices=[('GOOGLE_PLACES', 'Google Places'), ('FOURSQUARE', 'Foursquare Places'), ('CNPJ', 'Dataset CNPJ (Receita Federal)'), ('MANUAL', 'Cadastro manual')], default='GOOGLE_PLACES', help_text='Fonte consultada nesta varredura.', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='origem',
            field=models.CharField(choices=[('GOOGLE_PLACES', 'Google Places'), ('FOURSQUARE', 'Foursquare Places'), ('CNPJ', 'Dataset CNPJ (Receita Federal)'), ('MANUAL', 'Cadastro manual')], max_length=20),
        ),
    ]
