# Generated by Django 5.2.17 on 2026-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_varredura_fonte_alter_prospect_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectVerificacao',
            fields=[
            ],
            options={
                'verbose_name': 'fila de verificação de site',
                'verbose_name_plural': 'fila de verificação de site',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leads.prospect',),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status_funil',
            field=models.CharField(choices=[('VERIFICAR_SITE', 'Verificar site (pendente)'), ('NOVO', 'Novo (curadoria)'), ('INICIAR', 'A iniciar'), ('EM_ANDAMENTO', 'Em andamento'), ('REMARKETING', 'Remarketing'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='NOVO', max_length=20),
        ),
    ]
