# Generated by Django 5.2.17 on 2026-08-14 17:02

import leads.utils.telefone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_foursquare_pendente_de_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='fechado_na_fonte',
            field=models.CharField(blank=True, default='', help_text='Evidência de fechamento vinda da fonte. Vazio = a fonte não afirmou nada.', max_length=60),
        ),
        migrations.AddField(
            model_name='prospect',
            name='telefone_tipo',
            field=models.CharField(choices=[(leads.utils.telefone.TipoTelefone['CELULAR'], 'Celular (formato válido)'), (leads.utils.telefone.TipoTelefone['FIXO'], 'Fixo'), (leads.utils.telefone.TipoTelefone['LEGADO'], 'Celular formato antigo (sem o 9º dígito)'), (leads.utils.telefone.TipoTelefone['INVALIDO'], 'Formato não reconhecido'), (leads.utils.telefone.TipoTelefone['VAZIO'], 'Sem telefone')], db_index=True, default=leads.utils.telefone.TipoTelefone['VAZIO'], help_text='Formato do número. Não afirma que a linha existe ou tem WhatsApp.', max_length=10),
        ),
        migrations.AddField(
            model_name='varredura',
            name='total_fechados',
            field=models.PositiveIntegerField(default=0, help_text='Descartados na captação por estarem fechados na fonte.'),
        ),
    ]
