# Generated by Django 5.2.17 on 2026-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_normalizar_telefones_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='segmento',
            field=models.CharField(choices=[('SALAO', 'Salão de beleza'), ('BARBEARIA', 'Barbearia'), ('ESTETICA', 'Clínica de estética'), ('NAIL', 'Nail designer'), ('LASH', 'Lash designer'), ('SOBRANCELHA', 'Design de sobrancelha'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='varredura',
            name='segmento',
            field=models.CharField(choices=[('SALAO', 'Salão de beleza'), ('BARBEARIA', 'Barbearia'), ('ESTETICA', 'Clínica de estética'), ('NAIL', 'Nail designer'), ('LASH', 'Lash designer'), ('SOBRANCELHA', 'Design de sobrancelha'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
