# Generated by Django 5.2.17 on 2026-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_prospect_status_funil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status_funil',
            field=models.CharField(choices=[('VERIFICAR_SITE', 'Verificar site (pendente)'), ('NOVO', 'Novo (curadoria)'), ('INICIAR', 'A iniciar'), ('EM_ANDAMENTO', 'Em andamento'), ('SEM_RESPOSTA', 'Sem resposta'), ('NUMERO_INVALIDO', 'Número inválido'), ('REMARKETING', 'Remarketing'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='NOVO', max_length=20),
        ),
    ]
