# Generated by Django 5.2.17 on 2026-09-10 18:04

import django.db.models.deletion
from django.db import migrations, models


_TERMO_BELEZA_MARINGA = "Salão de beleza em Maringá PR"


def criar_nicho_e_fazer_backfill(apps, schema_editor):
    """Associa apenas o lote histórico cuja origem comercial é comprovada.

    O segmento atual do prospect não entra no critério: ele pode ter sido
    corrigido na curadoria. A evidência é a varredura de origem, cujo termo
    literal, fonte e área registram a campanha comercial de beleza.
    """
    Nicho = apps.get_model("leads", "Nicho")
    Prospect = apps.get_model("leads", "Prospect")
    Varredura = apps.get_model("leads", "Varredura")

    beleza, _ = Nicho.objects.get_or_create(
        codigo="beleza",
        defaults={"nome": "Beleza", "ativo": True},
    )

    varreduras_comerciais = Varredura.objects.filter(
        termo_busca=_TERMO_BELEZA_MARINGA,
        fonte="FOURSQUARE",
        segmento="SALAO",
        cidade="Maringá",
        estado="PR",
    )
    varreduras_comerciais.update(nicho_id=beleza.pk)

    Prospect.objects.filter(varredura__in=varreduras_comerciais).update(
        nicho_id=beleza.pk
    )

    ambiguos = list(
        Prospect.objects.filter(nicho__isnull=True).values_list("pk", flat=True)[:20]
    )
    if ambiguos:
        raise RuntimeError(
            "Backfill de nicho interrompido: existem prospect(s) sem evidência "
            f"comercial suficiente: {', '.join(str(pk) for pk in ambiguos)}"
        )


def reverter_backfill(apps, schema_editor):
    """Limpa as associações antes de a operação reversa remover o modelo."""
    Prospect = apps.get_model("leads", "Prospect")
    Varredura = apps.get_model("leads", "Varredura")

    Prospect.objects.update(nicho=None)
    Varredura.objects.update(nicho=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_prospect_status_funil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'nicho',
                'verbose_name_plural': 'nichos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='prospect',
            name='nicho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='leads.nicho'),
        ),
        migrations.AddField(
            model_name='varredura',
            name='nicho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='varreduras', to='leads.nicho'),
        ),
        migrations.RunPython(criar_nicho_e_fazer_backfill, reverter_backfill),
        migrations.AlterField(
            model_name='prospect',
            name='nicho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='leads.nicho'),
        ),
    ]
