# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_nicho_prospect_nicho_varredura_nicho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="endereco",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="bairro",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="estado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="pais",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="cep",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="origem_localizacao",
            field=models.CharField(
                choices=[
                    ("DESCONHECIDA", "Desconhecida"),
                    ("FONTE", "Fonte"),
                    ("MANUAL", "Manual"),
                ],
                default="DESCONHECIDA",
                help_text="Quem declarou a localização factual atualmente armazenada.",
                max_length=20,
            ),
        ),
    ]
