"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-inseguro-somente-local")

DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# --- Captação (Google Places API) -------------------------------------------
# A chave nunca é logada; o código registra apenas presença (regra de segredos).
GOOGLE_PLACES_API_KEY = os.getenv("GOOGLE_PLACES_API_KEY", "")

# Teto de requisições/mês. 1 requisição = 1 página = até 20 resultados.
# É a trava que mantém a fatura em zero dentro da franquia gratuita.
PLACES_FRANQUIA_MENSAL = int(os.getenv("PLACES_FRANQUIA_MENSAL", "1000"))


# --- Captação (Foursquare Places API) — fonte de contingência ---------------
# Cada fonte tem franquia PRÓPRIA. Somar as duas no mesmo contador travaria a
# captação cedo demais numa e tarde demais na outra.
FOURSQUARE_API_KEY = os.getenv("FOURSQUARE_API_KEY", "")

FOURSQUARE_FRANQUIA_MENSAL = int(os.getenv("FOURSQUARE_FRANQUIA_MENSAL", "10000"))

# Host da API. O padrão é a geração atual. Chave v3 legada exige apontar para
# https://api.foursquare.com/v3 — o cliente troca o estilo de auth sozinho.
FOURSQUARE_API_BASE = os.getenv(
    "FOURSQUARE_API_BASE", "https://places-api.foursquare.com"
)

# `rating` e `stats` da Foursquare são campos PAGOS (crédito de API). Sem
# crédito na conta, pedi-los devolve 429 e derruba a busca inteira. Desligado
# = captação gratuita, sem nota nem contagem de avaliações.
FOURSQUARE_CAMPOS_PRO = os.getenv("FOURSQUARE_CAMPOS_PRO", "False") == "True"

CIDADE_PADRAO = os.getenv("CIDADE_PADRAO", "Maringá")
ESTADO_PADRAO = os.getenv("ESTADO_PADRAO", "PR")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'leads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
